/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4aace2e2-a6da-4cc8-9859-100e62c29aa6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_018pwkLZl",
    "aws_user_pools_web_client_id": "1jdoujl1dc6r6fj15b890t7fue",
    "oauth": {}
};


export default awsmobile;
